NNStore/Areas/Admin/Controllers/ProductAdminController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NNStore.Context;
using static NNStore.Common;

namespace NNStore.Areas.Admin.Controllers
{
    public class ProductAdminController : Controller
    {
        // GET: Admin/Product
        NNStoreEntities ojbNNStoreEntities = new NNStoreEntities();

        public ActionResult Index(string currentFilter, string SearchString, int? page)
        {
            var lstProduct = new List<Product >();
            if (SearchString != null)
            {
                page = 1;
            }
            else
            {
                SearchString = currentFilter;

            }
            if (!string.IsNullOrEmpty(SearchString))
            {
                lstProduct = ojbNNStoreEntities.Products.Where(n => n.Name.Contains(SearchString)).ToList();
            }
            else
            {
                lstProduct = ojbNNStoreEntities.Products.ToList();
            }
            ViewBag.CurrentFilter = SearchString;
            int pageSize = 6;
            int pageNumber = (page ?? 1);
            lstProduct = lstProduct.OrderByDescending(n => n.Id).ToList();
            return View(lstProduct.ToPagedList(pageNumber, pageSize));
        }
     
        [HttpGet]
        public ActionResult Create()
        {
            this.LoadData();
            return View();
        }
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Create(Product objproduct)
        {
            this.LoadData();

            try
            {
                if (objproduct.ImageUpload != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(objproduct.ImageUpload.FileName);
                    string extention = Path.GetExtension(objproduct.ImageUpload.FileName);
                    fileName = fileName + "_" + long.Parse(DateTime.Now.ToString("yyyyMMddhhmmss")) + extention;
                    objproduct.Img = fileName;
                    objproduct.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/Content/img/Update"), fileName));
               
                ojbNNStoreEntities.Products.Add(objproduct);
                ojbNNStoreEntities.SaveChanges();
                return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }


            }
            catch (Exception)
            {

                return View();
            }

        }
        [HttpGet]
        public ActionResult Details(int id)
        {
            var ojbProduct = ojbNNStoreEntities.Products.Where(n => n.Id == id).FirstOrDefault();
            return View(ojbProduct);
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var ojbProduct = ojbNNStoreEntities.Products.Where(n => n.Id == id).FirstOrDefault();
            return View(ojbProduct);
        }
        [HttpPost]
        public ActionResult Delete(Product  objPro)
        {
            var ojbProduct = ojbNNStoreEntities.Products.Where(n => n.Id == objPro.Id).FirstOrDefault();
            ojbNNStoreEntities.Products.Remove(ojbProduct);
            ojbNNStoreEntities.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            this.LoadData();
            var ojbProduct = ojbNNStoreEntities.Products.Where(n => n.Id == id).FirstOrDefault();
            Session["anhgoc"] = ojbProduct.Img;
            return View(ojbProduct);
        }
        [ValidateInput(false)]
        [HttpPost]
        
        public ActionResult Edit(int id, Product objProduct)
        {
            this.LoadData();
           
            try
            {
                if (objProduct.ImageUpload != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(objProduct.ImageUpload.FileName);
                    string extention = Path.GetExtension(objProduct.ImageUpload.FileName);
                    fileName = fileName + extention;
                    objProduct.Img = fileName;
                    objProduct.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/Content/img/Product"), fileName));
                   
                }
                //else
                //{
                //    objProduct.Avatar = Session["anhgoc"].ToString();
                //}
                objProduct.UpdatedAt = DateTime.Now;
                ojbNNStoreEntities.Entry(objProduct).State = EntityState.Modified;
                ojbNNStoreEntities.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        void LoadData()
        {

            Common objCommon = new Common();
            var lstCat = ojbNNStoreEntities.Categories.ToList();
            ListtoDataTableConverter converter = new ListtoDataTableConverter();
            DataTable dtCategory = converter.ToDataTable(lstCat);
            ViewBag.ListCategory = objCommon.ToSelectList(dtCategory, "Id", "Name");

            var lstBrand = ojbNNStoreEntities.Brands.ToList();

            DataTable dtBrand = converter.ToDataTable(lstBrand);
            ViewBag.ListBrand = objCommon.ToSelectList(dtBrand, "Id", "Name");

            List<ProductType> lstProductType = new List<ProductType>();
            ProductType objProductType = new ProductType();
            objProductType.Id = 01;
            objProductType.Name = "Giảm giá";
            lstProductType.Add(objProductType);
            objProductType = new ProductType();
            objProductType.Id = 02;
            objProductType.Name = "Đề xuất";
            lstProductType.Add(objProductType);

            DataTable dtProductType = converter.ToDataTable(lstProductType);
            ViewBag.ProductType = objCommon.ToSelectList(dtProductType, "Id", "Name");

        }
    }
}

NNStore/Areas/Admin/Views/ProductAdmin/Create.cshtml
@model NNStore.Context.Product

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/ckeditor/ckeditor.js"></script>
<section class="section-content padding-y">
    <div class="card mx-auto" style="max-width:3500px; margin-left:50px;">
        <article class="card-body">
            <div class="content-wrapper">
                <header class="mb-4"><h4 class="text-danger">Thêm Dữ liệu</h4></header>

                @using (Html.BeginForm("Create", "ProductAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                    <hr />

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Img, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="file" name="ImageUpload" />
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.CategoryId, ViewBag.ListCategory as SelectList, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.BrandId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.BrandId, ViewBag.ListBrand as SelectList, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.BrandId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ShortDes, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ShortDes, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ShortDes, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.FullDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.FullDescription, new { htmlAttributes = new { @class = "form-control", @id = "FullDescription" } })
                            <script type="text/javascript" lang="javascript">
                                CKEDITOR.replace("FullDescription");
                            </script>
                            @Html.ValidationMessageFor(model => model.FullDescription, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.PriceSale, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.PriceSale, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PriceSale, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    @*<div class="form-group">
                        @Html.LabelFor(model => model.TypeId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.Id, ViewBag.ProductType as SelectList, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
                        </div>
                    </div>*@

                    <div class="form-group">
                        @Html.LabelFor(model => model.Slug, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Slug, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Slug, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Thêm" class="btn btn-default" />
                        </div>
                    </div>
                }


                <button>
                    @Html.ActionLink("Quay lại", "Index")
                </button>
            </div>
        </article>
    </div>
</section>

NNStore/Areas/Admin/Views/ProductAdmin/Delete.cshtml
@model NNStore.Context.Product

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<section class="section-content padding-y">
    <div class="card mx-auto" style="max-width:3500px; margin-left:50px;">
        <article class="card-body">
            <div class="content-wrapper">
                <header class="mb-4"><h4 class="text-danger">Xoá sản phẩm</h4></header>

                <h3>Bạn có chắc là xoá sản phẩm này không ?</h3>
                <div>
                    <h4>Thông tin sản phẩm</h4>
                    <hr />    <dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.Name)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Name)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Slug)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Slug)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.ShortDes)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.ShortDes)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.FullDescription)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.FullDescription)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.CategoryId)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.CategoryId)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Img)
    </dt>

    <dd>
    
        <img id="Avatar" class="hide" src="~/Content/img/Product/@Model.Img" width="107" height="98" alt="" />
    
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.BrandId)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.BrandId)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.TypeId)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.TypeId)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Price)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Price)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.PriceSale)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.PriceSale)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.CreatedBy)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.CreatedBy)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.CreatedAy)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.CreatedAy)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.UpdatedBy)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.UpdatedBy)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.UpdatedAt)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.UpdatedAt)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Deleted)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Deleted)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Status)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Status)
    </dd>

</dl>

                    @using (Html.BeginForm("Delete", "ProductAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            <input type="submit" value="Xoá" class="btn btn-default" />
                            <button> @Html.ActionLink("Quay lại", "Index")</button>

                        </div>
                    }
                </div>
            </div>
        </article>
    </div>
</section>

NNStore/Areas/Admin/Views/ProductAdmin/Index.cshtml
@using PagedList.Mvc;
@using PagedList;
@model PagedList.IPagedList<NNStore.Context.Product>
<style>
    .pagination {
        display: inline-block;
        padding-left: 0;
        margin: 20px 0;
        border-radius: 4px;
    }

        .pagination > li {
            display: inline;
        }

            .pagination > li > a,
            .pagination > li > span {
                position: relative;
                float: left;
                padding: 6px 12px;
                margin-left: -1px;
                line-height: 1.428571429;
                text-decoration: none;
                background-color: #ffffff;
                border: 1px solid #dddddd;
            }

            .pagination > li:first-child > a,
            .pagination > li:first-child > span {
                margin-left: 0;
                border-bottom-left-radius: 4px;
                border-top-left-radius: 4px;
            }

            .pagination > li:last-child > a,
            .pagination > li:last-child > span {
                border-top-right-radius: 4px;
                border-bottom-right-radius: 4px;
            }

            .pagination > li > a:hover,
            .pagination > li > span:hover,
            .pagination > li > a:focus,
            .pagination > li > span:focus {
                background-color: #eeeeee;
            }

        .pagination > .active > a,
        .pagination > .active > span,
        .pagination > .active > a:hover,
        .pagination > .active > span:hover,
        .pagination > .active > a:focus,
        .pagination > .active > span:focus {
            z-index: 2;
            color: #ffffff;
            cursor: default;
            background-color: #428bca;
            border-color: #428bca;
        }

        .pagination > .disabled > span,
        .pagination > .disabled > a,
        .pagination > .disabled > a:hover,
        .pagination > .disabled > a:focus {
            color: #999999;
            cursor: not-allowed;
            background-color: #ffffff;
            border-color: #dddddd;
        }

    .pagination-lg > li > a,
    .pagination-lg > li > span {
        padding: 10px 16px;
        font-size: 10px;
    }

    .pagination-lg > li:first-child > a,
    .pagination-lg > li:first-child > span {
        border-bottom-left-radius: 6px;
        border-top-left-radius: 6px;
    }

    .pagination-lg > li:last-child > a,
    .pagination-lg > li:last-child > span {
        border-top-right-radius: 6px;
        border-bottom-right-radius: 6px;
    }

    .pagination-sm > li > a,
    .pagination-sm > li > span {
        padding: 5px 10px;
        font-size: 12px;
    }

    .pagination-sm > li:first-child > a,
    .pagination-sm > li:first-child > span {
        border-bottom-left-radius: 3px;
        border-top-left-radius: 3px;
    }

    .pagination-sm > li:last-child > a, .pagination-sm > li:last-child > span {
        border-top-right-radius: 3px;
        border-bottom-right-radius: 3px;
    }

    .pager {
        padding-left: 0;
        margin: 20px 0;
        text-align: center;
        list-style: none;
    }

        .pager:before,
        .pager:after {
            display: table;
            content: " ";
        }

        .pager:after {
            clear: both;
        }

        .pager:before,
        .pager:after {
            display: table;
            content: " ";
        }

        .pager:after {
            clear: both;
        }

        .pager li {
            display: inline;
        }

            .pager li > a,
            .pager li > span {
                display: inline-block;
                padding: 5px 14px;
                background-color: #ffffff;
                border: 1px solid #dddddd;
                border-radius: 15px;
            }

                .pager li > a:hover,
                .pager li > a:focus {
                    text-decoration: none;
                    background-color: #eeeeee;
                }

        .pager .next > a,
        .pager .next > span {
            float: left;
        }

        .pager .disabled > a,
        .pager .disabled > a:hover,
        .pager .disabled > a:focus,
        .pager .disabled > span {
            color: #999999;
            cursor: not-allowed;
            background-color: #ffffff;
        }
</style>


@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<p>
    @Html.ActionLink("Thêm mới", "Create")
</p>

<section class="section-content padding-y">
    <div class="card mx-auto" style="max-width:5500px; margin-left:50px;">
        <article class="card-body">
            <div class="content-wrapper">
                <header class="mb-4"><h4 class="text-danger">Trang quản lý sản phẩm</h4></header>
                <div class="form-group">

                    @using (Html.BeginForm("Index", "ProductAdmin" +
                        "", FormMethod.Get))
                    {
                        <p>
                            Tìm tên sản phẩm:@Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
                            <input type="submit" value="Tìm kiếm" />
                        </p>
                    }
                    <div class="col-md-offset-2 col-md-10">

                        @Html.ActionLink("Thêm", "Create")
                    </div>
                </div>
                <table class="table">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.FirstOrDefault().Name)
                        <th>
                            @Html.DisplayNameFor(model => model.FirstOrDefault().Img)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FirstOrDefault().CategoryId)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FirstOrDefault().ShortDes)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.FirstOrDefault().Price)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FirstOrDefault().PriceSale)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FirstOrDefault().TypeId)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FirstOrDefault().Slug)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FirstOrDefault().BrandId)
                        </th>

                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                <img id="Avatar" class="hide" src="~/Content/img/Product/@item.Img" width="107" height="98" alt="" />
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CategoryId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ShortDes)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FullDescription)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Price)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.TypeId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Slug)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.BrandId)
                            </td>

                            <td>
                                <button style="width:100px"> @Html.ActionLink("Sửa", "Edit", new { id = item.Id })</button>   <br />
                                <button style="width:100px"> @Html.ActionLink("Chi tiết", "Details", new { id = item.Id })</button>    <br />
                                <button style="width:100px"> @Html.ActionLink("Xoá", "Delete", new { id = item.Id })</button>



                            </td>
                        </tr>
                    }

                </table>
                <div class="center-block>
                    @(Model.PageCount<Model.PageNumber?0 : Model.PageNumber)of @Model.PageCount
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentFilter = ViewBag.CurrentFilter }))
                </div>

            </div>
        </article>
    </div>
</section>